server:
  port: 8700
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
eureka:
  client:
    # 指向eureka的服务地址
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka